import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import { checkRouter }  from './routes/check.js';
import { appealRouter } from './routes/appeal.js';
import { trackerRouter } from './routes/tracker.js';
import { parseRouter }      from './routes/parse.js';
import { parseFileRouter }  from './routes/parseFile.js';
import { authRouter }   from './routes/auth.js';

const app = express();
app.use(cors());
app.use(express.json());
app.use('/api/auth',    authRouter);
app.use('/api/check',   checkRouter);
app.use('/api/appeal',  appealRouter);
app.use('/api/tracker', trackerRouter);
app.use('/api/parse',        parseRouter);
app.use('/api/parse-file',   parseFileRouter);
app.get('/health', (_, res) => res.json({ ok: true }));
const PORT = process.env.PORT || 3001;
app.listen(PORT, () => console.log(`Appeally server :${PORT}`));
